#=========================================================================
# Testbench
#=========================================================================

name: testbench

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - testbench.sv

