#=========================================================================
# Macros
#=========================================================================

name: macros

#=========================================================================
# Commands
#=========================================================================

commands:
  - mkdir -p outputs && cd outputs
  - ln -sf ../*.db .
  - ln -sf ../*.lef .
  - ln -sf ../*.v .

