#=========================================================================
# Synopsys DC Query
#=========================================================================
# Author : Alex Carsello
# Date   : March 19, 2021
#

name: synopsys-dc-query

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.mwlib
  - design.ddc

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - bash run.sh

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

parameters:
  topographical: True
  # Multithreading available to the tool
  nthreads: 16
  suppress_msg: False
  # List of suppressed messages. Select carefully
  suppressed_msg:
    # MW techhnology file load messages abaout missing attributes 
    - TFCHK-072
    - TFCHK-014
    - TFCHK-049
    - TFCHK-050
    - TFCHK-012
    - TFCHK-073
    - TFCHK-092
    # orientation warning from MW
    - PSYN-651
    - PSYN-650
  order:
    - designer-interface.tcl
    - setup-session.tcl
    - read-ddc.tcl
    - reporting.tcl

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'dc_shell-xg-t' )           # tool check
  - assert File( 'inputs/adk' )              # must exist
  - assert File( 'inputs/design.mwlib' )     # must exist
  - assert File( 'inputs/design.ddc' )       # must exist

postconditions:

  - assert 'error:' not in File( 'logs/dc.log' )

