#=========================================================================
# Synopsys DC Query
#=========================================================================
# Author : Alex Carsello
# Date   : March 19, 2021
#

name: synopsys-dc-query

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.ddc

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - bash run.sh

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

parameters:
  topographical: True
  # Multithreading available to the tool
  nthreads: 16
  order:
    - read-ddc.tcl
    - reporting.tcl

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'dc_shell-xg-t' )           # tool check
  - assert File( 'inputs/adk' )              # must exist
  - assert File( 'inputs/design.ddc' )         # must exist

